name: Notification para eliminacion de clientes

on:
  push:
    paths:
      - '**/*.txt'

jobs:
  notify_team_delete:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Team on Client Deletion
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'Delete client')"
        run: |
          deleted_client=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '\.txt' | sed 's/\.txt$//')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"Cliente eliminado: $deleted_client\"}" \
               $DISCORD_WEBHOOK_URL
