name: Notification para borrado de clientes

on:
  push:
    paths:
      - '**/*.txt' 

jobs:
  notify_team:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Team on Client Deletion
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'Delete client')"
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content":"Un cliente ha sido eliminado"}' \
             $DISCORD_WEBHOOK_URL
