name: Notification para agregado de clientes

on:
  push:
    paths:
      - '**/*.txt'

jobs:
  notify_team_add:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Team on Client Addition
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'Add client')"
        run: |
          added_client=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '\.txt' | sed 's/\.txt$//')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"Nuevo cliente agregado: $added_client\"}" \
               $DISCORD_WEBHOOK_URL
