name: Notificacion creado cliente

on:
  push:
    paths:
      - '**/*.txt'  # Adjust the file pattern as needed

jobs:
  notify_team:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Team on adding client
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'New client')"
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content":"Un nuevo cliente se ha agregado"}' \
             $DISCORD_WEBHOOK_URL
