name: Notification para agregado de clientes

on:
  push:
    paths:
      - '**/*.txt'

jobs:
  notify_team_add:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Team on Client Addition
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'New client')"
        run:
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"Un cliente ha sido editado"}' 
               $DISCORD_WEBHOOK_URL
