name: Notification para edicion de clientes
on:
  push:
    paths:
      - '**/*.txt'  

jobs:
  notify_team_edit:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Team on Client Edit
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'Edit client')"
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content":"Un cliente ha sido editado"}' \
             $DISCORD_WEBHOOK_URL
