name: Notificacion Cliente editado

on:
  push:
    paths:
      - '**/*.txt'  

jobs:
  notify_team:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Team
      if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'Update client information')"
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content":"La informacion de un cliente ha sido editada."}' \
             $DISCORD_WEBHOOK_URL

    - name: Automate Commit
      if: "github.event_name == 'push' && contains(github.event.head_commit.message, 'Edit client information')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "lopezabraham@outlook.com"
        git config --global user.name "Lobo046"
        git add -A
        git commit -m "Update client information"
        git push origin HEAD

